name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # or your preferred version

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Upload dist to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: dist/*
          target: ${{ secrets.APP_PATH }}
          rm: true

      - name: Move files to target and cleanup
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mv ${{ secrets.APP_PATH }}/dist/* ${{ secrets.APP_PATH }}/
            rm -rf ${{ secrets.APP_PATH }}/dist